#!/usr/bin/env python3
from __future__ import annotations

import os
import re
import subprocess
import threading
from datetime import datetime
from pathlib import Path

from flask import Flask, Response, jsonify, redirect, render_template, request, url_for

APP_NAME = "ha-archive-search"
VERSIONS_ROOT = Path(os.environ.get("HA_SEARCH_VERSIONS_ROOT", "/versions"))
SEARCH_CLI = Path(os.environ.get("HA_SEARCH_CLI", "/usr/local/bin/ha-archive-search"))
TIMEOUT_SECONDS = int(os.environ.get("HA_SEARCH_TIMEOUT", "15"))
MAX_QUERY_LEN = int(os.environ.get("HA_SEARCH_MAX_QUERY_LEN", "200"))

app = Flask(__name__)

_search_lock = threading.Lock()

SLUG_RE = re.compile(r"[^a-z0-9_-]+")
UNDERSCORE_RE = re.compile(r"_+")

COMPACT_LINE_RE = re.compile(
    r"^\[(?P<version>[^\]]+)\]\s+"
    r"(?P<path>.*?):"
    r"(?P<line>\d+):"
    r"(?P<content>.*)$"
)

SUMMARY_RE = re.compile(
    r"(?P<count>\d+)\s+results?\s+across\s+(?P<versions>\d+)\s+versions?\s+•\s+duration\s+(?P<duration>[0-9.,]+)\s+s"
)


def now_timestamp() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


def filename_timestamp() -> str:
    return datetime.now().strftime("%Y-%m-%d_%H-%M")


def slugify_query(query: str) -> str:
    slug = query.lower()
    slug = SLUG_RE.sub("_", slug)
    slug = UNDERSCORE_RE.sub("_", slug)
    slug = slug.strip("_")
    slug = slug[:64].strip("_")
    return slug or "query"


def markdown_inline_code(value: str) -> str:
    if "`" not in value:
        return f"`{value}`"
    return f"`` {value} ``"


def documentation_label(options: dict[str, bool]) -> str:
    if options.get("exclude_docs"):
        return "excluded"
    if options.get("docs_only"):
        return "only"
    return "included"


def bool_label(value: bool) -> str:
    return "yes" if value else "no"


def markdown_fence_for(content: str) -> str:
    runs = re.findall(r"`+", content)
    max_run = max((len(run) for run in runs), default=0)
    return "`" * max(3, max_run + 1)


def build_markdown_export(query: str, options: dict[str, bool], stdout: str) -> str:
    fence = markdown_fence_for(stdout)
    stdout_block = stdout if stdout.endswith("\n") else f"{stdout}\n"

    return (
        "# ha-archive-search — Results\n"
        "\n"
        f"- Query: {markdown_inline_code(query)}\n"
        f"- Context: {markdown_inline_code(bool_label(options.get('context', False)))}\n"
        f"- Latest only: {markdown_inline_code(bool_label(options.get('latest', False)))}\n"
        f"- All versions: {markdown_inline_code(bool_label(options.get('all_versions', False)))}\n"
        f"- Documentation: {markdown_inline_code(documentation_label(options))}\n"
        f"- Export date: {markdown_inline_code(now_timestamp())}\n"
        "\n"
        f"{fence}text\n"
        f"{stdout_block}"
        f"{fence}\n"
        "\n"
        "---\n"
        "Export generated by ha-archive-search\n"
    )


def bool_from_form(name: str) -> bool:
    return request.form.get(name) == "on"


def validate_form() -> tuple[str, dict[str, bool], str]:
    query = (request.form.get("query") or "").strip()
    if not query:
        return "", {}, "Empty query."
    if len(query) > MAX_QUERY_LEN:
        return "", {}, f"Query too long. Maximum: {MAX_QUERY_LEN} characters."

    options = {
        "context": bool_from_form("context"),
        "latest": bool_from_form("latest"),
        "all_versions": bool_from_form("all_versions"),
        "exclude_docs": bool_from_form("exclude_docs"),
        "docs_only": bool_from_form("docs_only"),
    }

    if options["latest"] and options["all_versions"]:
        return "", {}, "Incompatible options: latest only and all versions."

    if options["exclude_docs"] and options["docs_only"]:
        return "", {}, "Incompatible options: exclude documentation and documentation only."

    return query, options, ""


def build_command(query: str, options: dict[str, bool]) -> list[str]:
    cmd = ["python3", str(SEARCH_CLI), "--query", query]

    if options.get("all_versions"):
        cmd.append("--all-versions")
    elif options.get("latest"):
        cmd.append("--latest")

    if options.get("exclude_docs"):
        cmd.append("--exclude-docs")
    if options.get("docs_only"):
        cmd.append("--docs-only")

    if options.get("context"):
        cmd.extend(["--mode", "context"])
    else:
        cmd.extend(["--mode", "compact"])

    return cmd


def run_search_cli(
    query: str, options: dict[str, bool]
) -> tuple[subprocess.CompletedProcess[str] | None, str, int]:
    if not VERSIONS_ROOT.exists():
        return None, f"Versions directory not accessible: {VERSIONS_ROOT}", 500

    if not SEARCH_CLI.exists():
        return None, f"Search engine not found: {SEARCH_CLI}", 500

    acquired = _search_lock.acquire(blocking=False)
    if not acquired:
        return None, "A search is already in progress. Please retry in a few seconds.", 429

    try:
        result = subprocess.run(
            build_command(query, options),
            timeout=TIMEOUT_SECONDS,
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:
            error = result.stderr.strip() or f"Engine returned exit code {result.returncode}."
            return result, error, 502

        return result, "", 200

    except subprocess.TimeoutExpired:
        return None, f"Search too long (>{TIMEOUT_SECONDS} s).", 504

    except Exception:
        return None, "Internal error during search.", 500

    finally:
        _search_lock.release()


def parse_compact_output(output: str) -> tuple[dict | None, dict | None]:
    """Parse le stdout compact du moteur en structure hiérarchique.

    Retourne (grouped, summary) où :
      - grouped = {version: {path: [{"line": str, "content": str}, ...]}}
      - summary = {"count": str, "versions": str, "duration": str} ou None

    Retourne (None, summary) si aucun match parsé (résultat vide ou mode contexte).
    """
    grouped = {}
    summary = None
    parsed_count = 0

    for raw_line in output.splitlines():
        line = raw_line.rstrip("\n")

        m_summary = SUMMARY_RE.fullmatch(line)
        if m_summary:
            summary = {
                "count": m_summary.group("count"),
                "versions": m_summary.group("versions"),
                "duration": m_summary.group("duration").replace(",", "."),
            }
            continue

        if not line or line.startswith("─") or line.startswith("═"):
            continue

        m = COMPACT_LINE_RE.match(line)
        if not m:
            continue

        version = m.group("version")
        path = m.group("path")
        line_no = m.group("line")
        content = m.group("content").rstrip()

        grouped.setdefault(version, {}).setdefault(path, []).append(
            {"line": line_no, "content": content}
        )
        parsed_count += 1

    if parsed_count == 0:
        return None, summary

    return grouped, summary


def empty_template(**kwargs):
    defaults = {
        "app_name": APP_NAME,
        "query": "",
        "output": "",
        "error": "",
        "parsed": None,
        "summary": None,
        "context": False,
        "latest": False,
        "all_versions": False,
        "exclude_docs": False,
        "docs_only": False,
    }
    defaults.update(kwargs)
    return render_template("index.html", **defaults)


@app.get("/")
def index():
    return empty_template()


@app.get("/search")
def search_get():
    return redirect(url_for("index"))


@app.post("/search")
def search():
    query, options, validation_error = validate_form()

    if validation_error:
        return empty_template(
            query=query,
            output="",
            error=validation_error,
            **{k: bool(options.get(k, False)) for k in ("context", "latest", "all_versions", "exclude_docs", "docs_only")},
        ), 400

    result, error, status_code = run_search_cli(query, options)
    if error:
        return empty_template(query=query, output="", error=error, **options), status_code

    output = result.stdout.strip() or "No results."

    parsed = None
    summary = None

    if not options.get("context"):
        parsed, summary = parse_compact_output(output)

    return empty_template(
        query=query,
        output=output,
        error="",
        parsed=parsed,
        summary=summary,
        **options,
    )


@app.get("/export")
def export_get():
    return redirect(url_for("index"))


@app.post("/export")
def export_markdown():
    query, options, validation_error = validate_form()

    if validation_error:
        return empty_template(
            query=query,
            output="",
            error=validation_error,
            **{k: bool(options.get(k, False)) for k in ("context", "latest", "all_versions", "exclude_docs", "docs_only")},
        ), 400

    result, error, status_code = run_search_cli(query, options)
    if error:
        return empty_template(query=query, output="", error=error, **options), status_code

    markdown = build_markdown_export(query, options, result.stdout)
    filename = f"ha_archive_search_{slugify_query(query)}_{filename_timestamp()}.md"

    return Response(
        markdown,
        status=200,
        headers={
            "Content-Type": "text/markdown; charset=utf-8",
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )


@app.get("/health")
def health():
    return jsonify({
        "status": "ok",
        "versions_root": str(VERSIONS_ROOT),
        "search_cli": str(SEARCH_CLI),
        "versions_root_exists": VERSIONS_ROOT.exists(),
        "search_cli_exists": SEARCH_CLI.exists(),
    })


def main() -> None:
    app.run(host="0.0.0.0", port=8099, debug=False)


if __name__ == "__main__":
    main()